image: ubuntu:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apt update -y && apt install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_PATH"
    - rsync -avz --delete . $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH --exclude '.env'
    - ssh $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
      cd $DEPLOY_PATH
      export $(grep -v '^#' .env | xargs)
      npm install
      npm run build
      pm2 restart interview-ready-front --update-env || pm2 start "npm run start" --name interview-ready-front
      pm2 save
      EOF
