image: registry.gitlab.com/gitlab-org/ci-cd/ssh-executor:latest

stages:
  - deploy
  - deploy-test

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_STRATEGY: clone
  before_script:
    - set -x
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ls -la ~/.ssh
    - ssh -T $DEPLOY_USER@$DEPLOY_HOST || echo "SSH failed"
  script:
    - echo "Start SSH command"
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST "
        set -xe

        echo '✅ Connected'
        echo '📁 DEPLOY_PATH = $DEPLOY_PATH'
        cd $DEPLOY_PATH

        echo '📍 Current directory:'
        pwd

        echo '📦 Listing contents:'
        ls -la

        echo '🔍 Git status check:'
        git status

        git checkout master
        git pull
        npm install
        npm run build
        pm2 restart 'interview-ready-front' || pm2 start npm --name="interview-ready-front" -- run start -- --port 3000
        pm2 save
      "

deploy_test:
  stage: deploy-test
  only:
    - preprod
  variables:
    GIT_STRATEGY: clone
  before_script:
    - set -x
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ls -la ~/.ssh
    - ssh -T $DEPLOY_USER@$DEPLOY_HOST || echo "SSH failed"
  script:
    - echo "Start SSH command"
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST "
        set -xe

        echo '✅ Connected'
        echo '📁 DEPLOY_PATH_PREPROD = $DEPLOY_PATH_PREPROD'
        cd $DEPLOY_PATH_PREPROD

        echo '📍 Current directory:'
        pwd

        echo '📦 Listing contents:'
        ls -la

        echo '🔍 Git status check:'
        git status

        git checkout preprod
        git pull
        npm install
        npm run build
        pm2 restart 'interview-ready-front-preprod' || pm2 start npm --name="interview-ready-front-preprod" -- run start -- --port 3001
        pm2 save
      "
