export enum ESKILL_LEVEL {
  JUNIOR = 1,
  MIDDLE,
  SENIOR,
}

export enum ETEST_SPEC {
  FRONT = 1,
  BACK,
  QA,
}

export enum EGPT_SETTINGS_TYPE {
  TEST = 'TEST',
  INTERVIEW = 'INTERVIEW',
  RESUME_CHECK = 'RESUME_CHECK',
  RESUME_CREATE = 'RESUME_CREATE',
  GPT_ANALYZE = 'GPT_ANALYZE',
  GPT_DAYLY_ADVICE = 'GPT_DAYLY_ADVICE',
}
